### ISSUE TITLE
TEST: IF <-> BL mode switch problem

### ISSUE THREAD

**Issue by cederom** [ARMmbed/DAPLink#300]
```
Board: Name=Nordic-nRF51822 Unique ID=107000005331312031343637323037203530303297969903
Application: Name=sam3u2c_mkit_dk_dongle_nrf5x_if
Bootloader: Name=sam3u2c_bl
Target: Name=Nordic-nRF51822
SubTest: load_interface
SubTest: set_mode
changing mode IF -> BL
Traceback (most recent call last):
  File "../test/run_test.py", line 701, in <module>
    main()
  File "../test/run_test.py", line 679, in main
    tester.run_tests()
  File "../test/run_test.py", line 228, in run_tests
    board.load_interface(if_path, test_info)
  File "/(..)/DAPLink.git/test/daplink_board.py", line 423, in load_interface
    self.set_mode(self.MODE_BL, test_info)
  File "/(..)/DAPLink.git/test/daplink_board.py", line 309, in set_mode
    with open(start_bl_path, 'wb') as _:
IOError: [Errno 21] Is a directory: '/Volumes/DAPLINK/START_BL.CFG'
```

**Comment by cederom** [comment]
(mandatory?) manual re-plugging USB cable seems to fix the issue.
maybe some additional reset required for `Nordic-nRF51822`?

**Comment by cederom** [comment]
```
SubTest: Load good file to restore state
Skipping USB test on this platform
Board: Name=Microbit Unique ID=9900000031324e4500599019000000620000000097969901
Application: Name=kl26z_microbit_if
Bootloader: Name=kl26z_bl
Target: Name=Microbit
SubTest: load_interface
SubTest: set_mode
changing mode IF -> BL
Traceback (most recent call last):
  File "../test/run_test.py", line 701, in <module>
    main()
  File "../test/run_test.py", line 679, in main
    tester.run_tests()
  File "../test/run_test.py", line 228, in run_tests
    board.load_interface(if_path, test_info)
  File "/Users/cederom/cederom/work/CeDeROM/work/ARM/lab/cederom/DAPLink.git/test/daplink_board.py", line 423, in load_interface
    self.set_mode(self.MODE_BL, test_info)
  File "/Users/cederom/cederom/work/CeDeROM/work/ARM/lab/cederom/DAPLink.git/test/daplink_board.py", line 309, in set_mode
    with open(start_bl_path, 'wb') as _:
IOError: [Errno 21] Is a directory: '/Volumes/MICROBIT/START_BL.CFG'
```

**Comment by cederom** [comment]
```
SubTest: test_fs_contents
File /Volumes/DAPLINK 1/MBED.HTM valid
File /Volumes/DAPLINK 1/DETAILS.TXT valid
Skipping non file item /Volumes/DAPLINK 1/.fseventsd
SubTest: test_details_txt
SubTest: parse_kvp_file
SubTest: test_details_txt
SubTest: parse_kvp_file
changing mode IF -> BL
unmount took 0.957107067108 s
Traceback (most recent call last):
  File "../test/run_test.py", line 701, in <module>
    main()
  File "../test/run_test.py", line 679, in main
    tester.run_tests()
  File "../test/run_test.py", line 238, in run_tests
    daplink_test(test_configuration, test_info)
  File "/(...)/DAPLink.git/test/test_daplink.py", line 157, in daplink_test
    test_file_type('hex', board.MODE_BL, board, test_info, start, bin_data)
  File "/(...)/DAPLink.git/test/test_daplink.py", line 416, in test_file_type
    test.run()
  File "/(...)/DAPLink.git/test/msd_test.py", line 158, in run
    self._run(test_info)
  File "/(...)/DAPLink.git/test/test_daplink.py", line 93, in _run
    super(DLMassStorageTester, self)._run(test_info)
  File "/(...)/DAPLink.git/test/msd_test.py", line 259, in _run
    if self._check_data_correct(self._expected_data, test_info):
  File "/(...)/DAPLink.git/test/test_daplink.py", line 109, in _check_data_correct
    board.set_mode(self._test_mode)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 323, in set_mode
    self.wait_for_remount(test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 508, in wait_for_remount
    raise Exception("Mount timed out")
Exception: Mount timed out
```

**Comment by cederom** [comment]
not only NRF boards affected, also happens for Freescale/NXP chip..
```
Board: Name=FRDM-K64F Unique ID=0240000028884e45001070116bf000478021000097969900
Application: Name=k20dx_frdmk64f_if
Bootloader: Name=k20dx_bl
Target: Name=FRDM-K64F
SubTest: load_interface
SubTest: set_mode
changing mode IF -> BL
Traceback (most recent call last):
  File "../test/run_test.py", line 701, in <module>
    main()
  File "../test/run_test.py", line 679, in main
    tester.run_tests()
  File "../test/run_test.py", line 228, in run_tests
    board.load_interface(if_path, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 423, in load_interface
    self.set_mode(self.MODE_BL, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 309, in set_mode
    with open(start_bl_path, 'wb') as _:
IOError: [Errno 21] Is a directory: '/Volumes/DAPLINK/START_BL.CFG'
```

**Comment by cederom** [comment]
looks like problem is related with media availability on UMS disk and msdos filesystem flush:
```
default	00:16:53.401130 +0200	DiskUnmountWatcher	DiskUnmountWatcher: callback
default	00:16:53.401494 +0200	DiskUnmountWatcher	DiskUnmountWatcher: callback find and release <private>
default	00:16:53.401819 +0200	DiskUnmountWatcher	NAHFindByLabelAndRelease: looking for label <private>
default	00:16:53.401594 +0200	kernel	disk3: media is not present.
default	00:16:53.401806 +0200	kernel	disk3: media is not present.
default	00:16:53.401817 +0200	kernel	disk3: media is not present.
default	00:16:53.401829 +0200	kernel	disk3: media is not present.
default	00:16:53.401836 +0200	kernel	disk3: media is not present.
default	00:16:53.401844 +0200	kernel	msdosfs_fat_uninit_vol: error 6 from msdosfs_fat_cache_flush

default	00:16:53.461315 +0200	fseventsd	disk logger: failed to open output file /Volumes/DAPLINK 1/.fseventsd/0000000007d127d6 (No such file or directory). mount point /Volumes/DAPLINK 1/.fseventsd
default	00:16:53.461672 +0200	fseventsd	disk logger: failed to open output file /Volumes/DAPLINK 1/.fseventsd/0000000007d127d6 (No such file or directory). mount point /Volumes/DAPLINK 1/.fseventsd
default	00:16:53.884895 +0200	icdd	#ICDebug - 51:{ICWiredBrowser.m} (USB terminate)
default	00:16:53.885023 +0200	icdd	#ICDebug - 344:{ICWiredBrowser.m} (--> USB Terminate)
default	00:16:53.885389 +0200	icdd	#ICDebug - 363:{ICWiredBrowser.m} (Reclaiming Resource: DAPLink CMSIS-DAP)
default	00:16:53.885509 +0200	icdd	#ICDebug - 363:{ICWiredBrowser.m} (Reclaiming Resource: DAPLink CMSIS-DAP)
default	00:16:53.885631 +0200	icdd	#ICDebug - 371:{ICWiredBrowser.m} (7 USB Descriptions Managed)
default	00:16:53.885725 +0200	icdd	#ICDebug - 373:{ICWiredBrowser.m} (<-- USB Terminate)
default	00:16:53.886102 +0200	icdd	#ICDebug - 504:{ICDDMessageCenter.m} (-Rem DAPLink CMSIS-DAP - 0x0/0x0/0x0 - 0x14140000 - ICDeviceDescriptionUndefined)
default	00:16:53.886304 +0200	icdd	#ICDebug - 504:{ICDDMessageCenter.m} (-Rem DAPLink CMSIS-DAP - 0x8/0x6/0x50 - 0x14140000 - ICDeviceDescriptionUndefined)
default	00:16:53.895231 +0200	mds	Processing storeRemoved:<private>
default	00:16:53.895251 +0200	kernel	disk2: media is not present.
default	00:16:53.895294 +0200	mds	Processing storeRemoved:<private>
default	00:16:53.895333 +0200	mds	Processing storeRemoved:<private>
default	00:16:53.895397 +0200	mds	Processing storeRemoved:<private>
default	00:16:53.895756 +0200	kernel	disk2: media is not present.
default	00:16:53.895777 +0200	kernel	disk2: media is not present.
default	00:16:53.895792 +0200	kernel	disk2: media is not present.
default	00:16:53.895800 +0200	kernel	disk2: media is not present.
default	00:16:53.896463 +0200	mds	Processing storeRemoved:<private>
default	00:16:53.896643 +0200	mds	Processing storeRemoved:<private>
default	00:16:53.896816 +0200	mds	Processing storeRemoved:<private>
default	00:16:53.896861 +0200	mds	Processing storeRemoved:<private>
default	00:16:53.896925 +0200	mds	Processing storeRemoved:<private>
default	00:16:53.897063 +0200	mds	Processing storeRemoved:<private>
default	00:16:53.897179 +0200	mds	Processing storeRemoved:<private>

default	00:16:53.901706 +0200	DiskUnmountWatcher	DiskUnmountWatcher: callback
default	00:16:53.902104 +0200	DiskUnmountWatcher	DiskUnmountWatcher: callback find and release <private>
default	00:16:53.902184 +0200	DiskUnmountWatcher	NAHFindByLabelAndRelease: looking for label <private>
default	00:16:53.895806 +0200	kernel	msdosfs_fat_uninit_vol: error 6 from msdosfs_fat_cache_flush
```

**Comment by cederom** [comment]
this happens randomly, more often when 3 boards are tested rather than only 1..
also looks like no re-plug is necessary..

**Comment by cederom** [comment]
```
Board: Name=Microbit Unique ID=9900000031324e4500599019000000620000000097969901
Application: Name=kl26z_microbit_if
Bootloader: Name=kl26z_bl
Target: Name=Microbit
SubTest: load_interface
SubTest: set_mode
changing mode IF -> BL
Traceback (most recent call last):
  File "../test/run_test.py", line 701, in <module>
    main()
  File "../test/run_test.py", line 679, in main
    tester.run_tests()
  File "../test/run_test.py", line 228, in run_tests
    board.load_interface(if_path, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 423, in load_interface
    self.set_mode(self.MODE_BL, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 309, in set_mode
    with open(start_bl_path, 'wb') as _:
IOError: [Errno 21] Is a directory: '/Volumes/MICROBIT/START_BL.CFG'

(venv-mac-27) iCeDeROM:tools cederom$ mbedls
+---------------+----------------------+----------------------+------------------------+--------------------------------------------------+-----------------+
| platform_name | platform_name_unique | mount_point          | serial_port            | target_id                                        | daplink_version |
+---------------+----------------------+----------------------+------------------------+--------------------------------------------------+-----------------+
| K64F          | K64F[0]              | /Volumes/DAPLINK 1   | /dev/tty.usbmodem14132 | 0240000028884e45001070116bf000478021000097969900 | 0243            |
| NRF51822      | NRF51822[0]          | /Volumes/DAPLINK     | /dev/tty.usbmodem14122 | 107000005331312031343637323037203530303297969903 | 0243            |
| unknown       | None[0]              | /Volumes/MAINTENANCE | unknown                | 0000000031324e4500599019000000620000000097969901 | 0243            |
+---------------+----------------------+----------------------+------------------------+--------------------------------------------------+-----------------+
```

**Comment by cederom** [comment]
Removing the legacy mode switch in `set_mode()` does not fix, also `wait_for_remount()` needs review..?
```
Board: Name=Nordic-nRF51822 Unique ID=107000005331312031343637323037203530303297969903
Application: Name=sam3u2c_mkit_dk_dongle_nrf5x_if
Bootloader: Name=sam3u2c_bl
Target: Name=Nordic-nRF51822
SubTest: load_interface
SubTest: set_mode
changing mode IF -> BL
SubTest: wait_for_remount
unmount took 0.731024980545 s
mount took 2.45878100395 s
Expected remount count of 16 got 15
Board in wrong mode: interface
Traceback (most recent call last):
  File "../test/run_test.py", line 701, in <module>
    main()
  File "../test/run_test.py", line 679, in main
    tester.run_tests()
  File "../test/run_test.py", line 228, in run_tests
    board.load_interface(if_path, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 413, in load_interface
    self.set_mode(self.MODE_BL, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 318, in set_mode
    raise Exception("Could not change board mode")
Exception: Could not change board mode

(venv-mac-27) iCeDeROM:tools cederom$ mbedls
+----------------+----------------------+----------------------+------------------------+--------------------------------------------------+-----------------+
| platform_name  | platform_name_unique | mount_point          | serial_port            | target_id                                        | daplink_version |
+----------------+----------------------+----------------------+------------------------+--------------------------------------------------+-----------------+
| NRF51822       | NRF51822[0]          | /Volumes/DAPLINK     | /dev/tty.usbmodem14222 | 107000005331312031343637323037203530303297969903 | 0243            |
| NRF51_MICROBIT | NRF51_MICROBIT[0]    | /Volumes/MICROBIT    | /dev/tty.usbmodem14242 | 9900000031324e4500599019000000620000000097969901 | 0243            |
| unknown        | None[0]              | /Volumes/MAINTENANCE | unknown                | 0000000028884e45001070116bf000478021000097969900 | 0243            |
+----------------+----------------------+----------------------+------------------------+--------------------------------------------------+-----------------+
```

**Comment by cederom** [comment]
got this problem again, probably caused by manual test interruption on bootloader upgrade.. bootloader verification on test start should fix the problem..
```
Board: Name=Microbit Unique ID=9900000031324e4500599019000000620000000097969901
Application: Name=kl26z_microbit_if
Bootloader: Name=kl26z_bl
Target: Name=Microbit
SubTest: load_interface
SubTest: set_mode
changing mode IF -> BL
SubTest: wait_for_remount
unmount took 0.925055980682 s
mount took 4.19406199455 s
Expected remount count of 1 got 0
Board in wrong mode: interface
Traceback (most recent call last):
  File "../test/run_test.py", line 701, in <module>
    main()
  File "../test/run_test.py", line 679, in main
    tester.run_tests()
  File "../test/run_test.py", line 228, in run_tests
    board.load_interface(if_path, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 413, in load_interface
    self.set_mode(self.MODE_BL, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 318, in set_mode
    raise Exception("Could not change board mode")
Exception: Could not change board mode

(venv-mac-27) iCeDeROM:tools cederom$ mbedls
+----------------+----------------------+-------------------+------------------------+--------------------------------------------------+-----------------+
| platform_name  | platform_name_unique | mount_point       | serial_port            | target_id                                        | daplink_version |
+----------------+----------------------+-------------------+------------------------+--------------------------------------------------+-----------------+
| K64F           | K64F[0]              | /Volumes/DAPLINK  | /dev/tty.usbmodem14132 | 0240000028884e45001070116bf000478021000097969900 | 0243            |
| NRF51_MICROBIT | NRF51_MICROBIT[0]    | /Volumes/MICROBIT | /dev/tty.usbmodem14142 | 9900000031324e4500599019000000620000000097969901 | 0243            |
+----------------+----------------------+-------------------+------------------------+--------------------------------------------------+-----------------+

(venv-mac-27) iCeDeROM:tools cederom$ ls /Volumes/MICROBIT/
DETAILS.TXT	MICROBIT.HTM	NEED_BL.TXT
```

**Comment by cederom** [comment]
Another fix regarding corrupted bootloader (as presented above) was proposed and merged to upstream: https://github.com/mbedmicro/DAPLink/pull/307

**Comment by cederom** [comment]
seems to be fixed? does not occur anymore..
