### ISSUE TITLE
Test / Intermittent / Host Power Management

### ISSUE THREAD

**Issue by cederom** [ARMmbed/DAPLink#308]
This one is hihgly likely related with macOS Power Management - USB port was put to sleep after hours of testing - all Power Management features like `Sleep Mode` or `Power Nap` on `Power Adapter` must be disabled on a testing host..

```
----- Restoring image -----
HID test complete
SubTest: Serial test
Testing serial port /dev/tty.usbmodem14142
Testing baud 9600
SubTest: Set Baud
Pass
Testing baud 14400
SubTest: Set Baud
Pass
Testing baud 19200
SubTest: Set Baud
Pass
Testing baud 28800
SubTest: Set Baud
Pass
Testing baud 38400
SubTest: Set Baud
Pass
Testing baud 57600
SubTest: Set Baud
Pass
Testing baud 115200
SubTest: Set Baud
Pass
Timing test baud 28800
SubTest: Set Baud
Traceback (most recent call last):
  File "../test/run_test.py", line 701, in <module>
    main()
  File "../test/run_test.py", line 679, in main
    tester.run_tests()
  File "../test/run_test.py", line 241, in run_tests
    test_endpoints(test_configuration, test_info)
  File "../test/run_test.py", line 93, in test_endpoints
    test_serial(workspace, test_info)
  File "/(...)/DAPLink.git/test/serial_test.py", line 237, in test_serial
    resp += sp.read(1)
  File "/(...)/DAPLink.git/test/serial_test.py", line 135, in read
    return self.raw_serial.read(length)
  File "/(...)/venv-mac-27/lib/python2.7/site-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: [Errno 6] Device not configured

(venv-mac-27) iCeDeROM:tools cederom$ mbedls
+----------------+----------------------+-------------------+------------------------+--------------------------------------------------+-----------------+
| platform_name  | platform_name_unique | mount_point       | serial_port            | target_id                                        | daplink_version |
+----------------+----------------------+-------------------+------------------------+--------------------------------------------------+-----------------+
| K64F           | K64F[0]              | /Volumes/DAPLINK  | /dev/tty.usbmodem14132 | 0240000028884e45001070116bf000478021000097969900 | 0243            |
| NRF51_MICROBIT | NRF51_MICROBIT[0]    | /Volumes/MICROBIT | /dev/tty.usbmodem14142 | 9900000031324e4500599019000000620000000097969901 | 0243            |
+----------------+----------------------+-------------------+------------------------+--------------------------------------------------+-----------------+
```

**Comment by cederom** [comment]
Power management on the CI Host will interrupt tests, needs to be disabled for reliable testing..
